### ISSUE TITLE
RuntimeException with Quarkus 3.1.0.Final

### ISSUE THREAD

**Issue by krisgerhard** [quarkiverse/quarkus-logging-logback#127]
I'm getting this error while running tests on 3.1.0.Final.
Everything works with previous release.

```
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.logging.logback.deployment.LoggingLogbackProcessor#init threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.bootstrap.model.AppModel io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem.getEffectiveModel()'
	at io.quarkiverse.logging.logback.deployment.LoggingLogbackProcessor.init(LoggingLogbackProcessor.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:223)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:607)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	... 37 more
```

**Comment by krisgerhard** [comment]
@stuartwdouglas ? :)

**Comment by gsmet** [comment]
@krisgerhard Quarkus 3.1.0.Final will be released today (until today, only the core artifacts were released, not the full Platform). I will cut a compatible release of quarkus-logging-logback too.

**Comment by gsmet** [comment]
1.1.0 is on its way to Maven Central. It should be available in ~30 minutes. Thanks for raising the issue.

**Comment by krisgerhard** [comment]
Thank you @gsmet! "3.1.0.Final not released" is interesting because for me all the artifacts were available on Maven Central since 24th May - bom, plugins. Or what did you mean by "full Platform"?

I've noticed previously as well that my dependency bot notifies me a lot earlier than official releases in GitHub appear. I think I've even ran these versions in production before the "full release".

**Comment by gsmet** [comment]
@krisgerhard except if you are developing publicly consumable extensions (like this one), you should rely on the Platform BOM, which is `io.quarkus.platform:quarkus-bom` (note the `.platform`). Same for the Maven plugin, you should consume the `io.quarkus.platform` one. That's what you will get if you create your apps with the Quarkus dev tools or code.quarkus.io.

The Platform is the full Quarkus release, with several additional extensions with versions properly aligned to be consistent, extensions that you can use or not. Most of the time, it doesn't change a thing as I release them the same day. But for `.0.Final`, there is a one-week delay between the core release and the Platform release (and the announcement) so that all the extension ecosystem can update to the new version and make sure the ecosystem is ready.

**Comment by gsmet** [comment]
Note that, in your case, if wouldn't have changed a thing to wait as I completely forgot about this fix :).

**Comment by krisgerhard** [comment]
> @krisgerhard except if you are developing publicly consumable extensions (like this one), you should rely on the Platform BOM, which is `io.quarkus.platform:quarkus-bom` (note the `.platform`). Same for the Maven plugin, you should consume the `io.quarkus.platform` one. That's what you will get if you create your apps with the Quarkus dev tools or code.quarkus.io.
> 
> The Platform is the full Quarkus release, with several additional extensions with versions properly aligned to be consistent, extensions that you can use or not. Most of the time, it doesn't change a thing as I release them the same day. But for `.0.Final`, there is a one-week delay between the core release and the Platform release (and the announcement) so that all the extension ecosystem can update to the new version and make sure the ecosystem is ready.

Thanks for the info! Eye-opening :)

> Note that, in your case, if wouldn't have changed a thing to wait as I completely forgot about this fix :).

Quarkiverse [blog](https://quarkus.io/blog/quarkiverse/) states:

> Quarkiverse extensions are built daily against the latest [Quarkus core](https://github.com/quarkusio/quarkus) using the [Quarkus Ecosystem CI](https://github.com/quarkusio/quarkus-ecosystem-ci) and listed in the [Quarkus Status](https://status.quarkus.io/) page.

Is this not the case for this extension? Given it is not relying on platform version this issue should have risen automatically.
