### ISSUE TITLE
Compression seems to be missing in somehow

### ISSUE THREAD

**Issue by MintakaB** [quarkiverse/quarkus-logging-logback#193]
HI,
Congratulations for this project and I hope to see updates soon since it seems no work is done recently.

I discovered very recently and I am quite exited to start to used it. I was doing some basic tests and I realise that compression fails . 

cheers and thank you for any feedback!

```
  <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
        <fileNamePattern>logs/test-manager.%d{yyyy-MM-dd}.log.gz</fileNamePattern>
```

```
2024-09-02 11:39:12,318 [Aesh InputStream Reader] DEBUG java.lang.Runtime - -Runtime.exit() called with status: 0
java.lang.Throwable: Runtime.exit(0)
	at java.base/java.lang.Shutdown.logRuntimeExit(Shutdown.java:179)
	at java.base/java.lang.Shutdown.exit(Shutdown.java:160)
	at java.base/java.lang.Runtime.exit(Runtime.java:188)
	at java.base/java.lang.System.exit(System.java:1920)
	at io.quarkus.deployment.console.ConsoleStateManager$3.run(ConsoleStateManager.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at io.quarkus.deployment.console.ConsoleStateManager.exitQuarkus(ConsoleStateManager.java:186)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:77)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:49)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$1(AeshConsole.java:278)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-02 11:39:12,323 [Aesh Shutdown Hook] DEBUG o.a.r.terminal.utils.ShutdownHooks - -Running all shutdown-hook tasks
2024-09-02 11:39:12,323 [Aesh Shutdown Hook] DEBUG o.a.r.terminal.utils.ShutdownHooks - -Running all shutdown-hook tasks
2024-09-02 11:39:12,323 [Shutdown thread] DEBUG io.quarkus.runtime.Application - -Stopping application
2024-09-02 11:39:12,323 [Quarkus Main Thread] DEBUG io.quarkus.runtime.Application - -Stopping application
2024-09-02 11:39:12,324 [Console Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Running: [stty, -f, /dev/ttys016, -a]
2024-09-02 11:39:12,324 [Aesh Shutdown Hook] DEBUG o.a.r.terminal.utils.ShutdownHooks - -Running task: 
2024-09-02 11:39:12,324 [Shutdown thread] DEBUG i.q.r.shutdown.ShutdownRecorder - -Attempting to gracefully shutdown.
2024-09-02 11:39:12,325 [Aesh Shutdown Hook] DEBUG o.a.r.terminal.utils.ShutdownHooks - -Removing shutdown-hook: 
2024-09-02 11:39:12,325 [Aesh Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Running: [stty, -f, /dev/ttys016, -a]
2024-09-02 11:39:12,331 [Console Shutdown Hook] DEBUG java.lang.ProcessBuilder - -ProcessBuilder.start(): pid: 20852, dir: null, cmd: "stty"
java.lang.RuntimeException: ProcessBuilder.start() debug
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:456)
	at org.aesh.readline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:245)
	at org.aesh.readline.terminal.impl.ExecPty.getAttr(ExecPty.java:131)
	at org.aesh.readline.terminal.impl.ExecPty.setAttr(ExecPty.java:153)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
	at org.aesh.readline.tty.terminal.TerminalConnection.setAttributes(TerminalConnection.java:180)
	at io.quarkus.deployment.console.AeshConsole.end(AeshConsole.java:167)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$2(AeshConsole.java:303)
	at org.aesh.readline.tty.terminal.TerminalConnection.close(TerminalConnection.java:346)
	at io.quarkus.deployment.console.AeshConsole$2.run(AeshConsole.java:88)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-02 11:39:12,332 [Aesh Shutdown Hook] DEBUG java.lang.ProcessBuilder - -ProcessBuilder.start(): pid: 20853, dir: null, cmd: "stty"
java.lang.RuntimeException: ProcessBuilder.start() debug
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:456)
	at org.aesh.readline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:245)
	at org.aesh.readline.terminal.impl.ExecPty.getAttr(ExecPty.java:131)
	at org.aesh.readline.terminal.impl.ExecPty.setAttr(ExecPty.java:153)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.close(AbstractPosixTerminal.java:69)
	at org.aesh.readline.terminal.impl.PosixSysTerminal.close(PosixSysTerminal.java:68)
	at org.aesh.readline.terminal.utils.ShutdownHooks.runTasks(ShutdownHooks.java:68)
	at org.aesh.readline.terminal.utils.ShutdownHooks.access$000(ShutdownHooks.java:34)
	at org.aesh.readline.terminal.utils.ShutdownHooks$1.run(ShutdownHooks.java:49)
2024-09-02 11:39:12,335 [Console Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Result: speed 38400 baud; 19 rows; 204 columns;
lflags: -icanon isig -iexten -echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo
	-extproc
iflags: -istrip -icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = <undef>; kill = ^U;
	lnext = ^V; min = 1; quit = ^\; reprint = ^R; start = ^Q;
	status = ^T; stop = ^S; susp = ^Z; time = 0; werase = ^W;

2024-09-02 11:39:12,335 [Aesh Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Result: speed 38400 baud; 19 rows; 204 columns;
lflags: -icanon isig -iexten -echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo
	-extproc
iflags: -istrip -icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = <undef>; kill = ^U;
	lnext = ^V; min = 1; quit = ^\; reprint = ^R; start = ^Q;
	status = ^T; stop = ^S; susp = ^Z; time = 0; werase = ^W;

2024-09-02 11:39:12,338 [Console Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Running: [stty, -f, /dev/ttys016, icrnl, ixon, echo, icanon, iexten, intr, ^C]
2024-09-02 11:39:12,338 [Aesh Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Running: [stty, -f, /dev/ttys016, icrnl, ixon, echo, icanon, iexten, pendin, intr, ^C]
2024-09-02 11:39:12,343 [Aesh Shutdown Hook] DEBUG java.lang.ProcessBuilder - -ProcessBuilder.start(): pid: 20855, dir: null, cmd: "stty"
java.lang.RuntimeException: ProcessBuilder.start() debug
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:456)
	at org.aesh.readline.terminal.impl.ExecPty.setAttr(ExecPty.java:210)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.close(AbstractPosixTerminal.java:69)
	at org.aesh.readline.terminal.impl.PosixSysTerminal.close(PosixSysTerminal.java:68)
	at org.aesh.readline.terminal.utils.ShutdownHooks.runTasks(ShutdownHooks.java:68)
	at org.aesh.readline.terminal.utils.ShutdownHooks.access$000(ShutdownHooks.java:34)
	at org.aesh.readline.terminal.utils.ShutdownHooks$1.run(ShutdownHooks.java:49)
2024-09-02 11:39:12,343 [Console Shutdown Hook] DEBUG java.lang.ProcessBuilder - -ProcessBuilder.start(): pid: 20854, dir: null, cmd: "stty"
java.lang.RuntimeException: ProcessBuilder.start() debug
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:456)
	at org.aesh.readline.terminal.impl.ExecPty.setAttr(ExecPty.java:210)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
	at org.aesh.readline.tty.terminal.TerminalConnection.setAttributes(TerminalConnection.java:180)
	at io.quarkus.deployment.console.AeshConsole.end(AeshConsole.java:167)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$2(AeshConsole.java:303)
	at org.aesh.readline.tty.terminal.TerminalConnection.close(TerminalConnection.java:346)
	at io.quarkus.deployment.console.AeshConsole$2.run(AeshConsole.java:88)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-02 11:39:12,345 [Console Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Result: 
2024-09-02 11:39:12,345 [Aesh Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Result: 
2024-09-02 11:39:12,346 [Console Shutdown Hook] DEBUG o.a.readline.terminal.impl.ExecPty - -Running: [stty, -f, /dev/ttys016, -a]
2024-09-02 11:39:12,350 [Console Shutdown Hook] DEBUG java.lang.ProcessBuilder - -ProcessBuilder.start(): pid: 20856, dir: null, cmd: "stty"
java.lang.RuntimeException: ProcessBuilder.start() debug
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:456)
	at org.aesh.readline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:245)
	at org.aesh.readline.terminal.impl.ExecPty.getAttr(ExecPty.java:131)
	at org.aesh.readline.terminal.impl.ExecPty.setAttr(ExecPty.java:153)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
	at org.aesh.readline.tty.terminal.TerminalConnection.close(TerminalConnection.java:354)
	at io.quarkus.deployment.console.AeshConsole$2.run(AeshConsole.java:88)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-02 11:39:12,351 [Shutdown thread] DEBUG io.quarkus.arc.impl - -ArC DI container shut down

```

**Comment by MintakaB** [comment]
Not an issue. It was a dependency problem.
