### ISSUE TITLE
ClassNotFoundException at app start when Logback looks for CompositeConverter

### ISSUE THREAD

**Issue by peterhuba** [quarkiverse/quarkus-logging-logback#46]
Hello,

When in the logback.xml I use a composite converter, for example:
```
    <conversionRule conversionWord="sensitiveDataReplace"
                    converterClass="org.acme.getting.started.SensitiveDataReplacingConverter"/>
```
then when Quarkus starts in dev mode, I get the following stacktrace:
```
17:41:22,532 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@3baabbe6 - Failed to instantiate converter class [org.acme.getting.started.SensitiveDataReplacingConverter] as a composite converter for keyword [sensitiveDataReplace] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.acme.getting.started.SensitiveDataReplacingConverter
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.acme.getting.started.SensitiveDataReplacingConverter
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.pattern.parser.Compiler.createCompositeConverter(Compiler.java:129)
	at 	at ch.qos.logback.core.pattern.parser.Compiler.compile(Compiler.java:47)
	at 	at ch.qos.logback.core.pattern.parser.Parser.compile(Parser.java:87)
	at 	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:84)
	at 	at net.logstash.logback.pattern.PatternLayoutAdapter.start(PatternLayoutAdapter.java:100)
	at 	at net.logstash.logback.pattern.AbstractJsonPatternParser.buildLayout(AbstractJsonPatternParser.java:224)
	at 	at net.logstash.logback.pattern.AbstractJsonPatternParser.makeLayoutValueGetter(AbstractJsonPatternParser.java:197)
	at 	at net.logstash.logback.pattern.AbstractJsonPatternParser.makeComputableValueGetter(AbstractJsonPatternParser.java:183)
	at 	at net.logstash.logback.pattern.AbstractJsonPatternParser.parseNode(AbstractJsonPatternParser.java:317)
	at 	at net.logstash.logback.pattern.AbstractJsonPatternParser.parseObject(AbstractJsonPatternParser.java:371)
	at 	at net.logstash.logback.pattern.AbstractJsonPatternParser.parse(AbstractJsonPatternParser.java:300)
	at 	at net.logstash.logback.composite.AbstractPatternJsonProvider.initializeNodeWriter(AbstractPatternJsonProvider.java:104)
	at 	at net.logstash.logback.composite.AbstractPatternJsonProvider.start(AbstractPatternJsonProvider.java:85)
	at 	at net.logstash.logback.composite.JsonProviders.start(JsonProviders.java:48)
	at 	at net.logstash.logback.composite.AbstractCompositeJsonFormatter.start(AbstractCompositeJsonFormatter.java:119)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.start(CompositeJsonEncoder.java:129)
	at 	at net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder$$delayed.doQuarkusDelayedStart(Unknown Source)
	at 	at io.quarkiverse.logback.runtime.LogbackRecorder.createHandler(LogbackRecorder.java:130)
	at 	at io.quarkus.deployment.steps.LoggingLogbackProcessor$handler1311068917.deploy_0(Unknown Source)
	at 	at io.quarkus.deployment.steps.LoggingLogbackProcessor$handler1311068917.deploy(Unknown Source)
	at 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at 	at io.quarkus.runtime.Application.start(Application.java:101)
	at 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at 	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at 	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.acme.getting.started.SensitiveDataReplacingConverter
	at 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:438)
	at 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 35 common frames omitted
```
The app does work, however the log appender that uses the converter of course does not work as expected.

Interestingly, when I run in prod mode with ` ./mvnw package -Dquarkus.package.type=uber-jar` and `java -jar target/*-runner.jar`, there's no stacktrace and the appender and the converter work as expected.

Reproduces on linux with the this code https://github.com/peterhuba/quarkus-logback-issues (latest commit on master).
Do you have any clue? Thanks!

**Comment by stuartwdouglas** [comment]
There is not much I can do here as the incorrect CL is hard coded into logback, I would need to transform the logback class to use the TCCL.

As a workaround you could move the `org.acme.getting.started.SensitiveDataReplacingConverter` class into a different maven artifact that is not hot reloadable (i.e. create a one class library).
