### ISSUE TITLE
IncompatibleClassChangeError while using logback with quarkus

### ISSUE THREAD

**Issue by himanshumps** [quarkiverse/quarkus-logging-logback#72]
Issue while using custom appender in 0.12.0

```
<appender name="CONSOLE" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="c.a.ea.elf.logback.ELFLogbackEncoder">
                <includeContext>false</includeContext>
                <shortenedLoggerNameLength>20</shortenedLoggerNameLength>
                <timestampPattern>[ISO_INSTANT]</timestampPattern>
                <fieldNames>
                    <version>[ignore]</version>
                    <levelValue>[ignore]</levelValue>
                    <!--<timestamp>timestamp</timestamp>-->
                    <thread>[ignore]</thread>
                </fieldNames>
            </encoder>
        </appender>
    </appender>
```

**Error**
```
ERROR: Error running Quarkus
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at c.t.p.p.Application.main(Application.java:52)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 16 more
Caused by: java.lang.IncompatibleClassChangeError: class c.a.ea.elf.logback.ELFLogbackEncoder$$delayed cannot inherit from final class c.a.ea.elf.logback.ELFLogbackEncoder
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:480)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
	at ch.qos.logback.core.util.Loader.loadClass(Loader.java:120)
	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.begin(NestedComplexPropertyIA.java:102)
	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at io.quarkiverse.logback.runtime.LogbackRecorder.init(LogbackRecorder.java:91)
	at io.quarkus.deployment.steps.LoggingLogbackProcessor$init519114389.deploy_4(Unknown Source)
	at io.quarkus.deployment.steps.LoggingLogbackProcessor$init519114389.deploy(Unknown Source)
	... 17 more

```

**Comment by stuartwdouglas** [comment]
Do you have control of the appender? If so remove the final flag. Otherwise I will need to add some transformation to remove it automatically.
